"""add_name_to_friend

Revision ID: 04112fe94efe
Revises: db59aa011c94
Create Date: 2025-09-06 18:36:36.732729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04112fe94efe'
down_revision: Union[str, Sequence[str], None] = 'db59aa011c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('friends', sa.Column('name', sa.String(length=50), nullable=True))
    
    # Update existing records with a default name
    op.execute("UPDATE friends SET name = 'Friend' WHERE name IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('friends', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'name')
    # ### end Alembic commands ###
