"""Add friend

Revision ID: 3754ae1d332e
Revises: d5cbedacf0a1
Create Date: 2025-09-06 12:46:37.871783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3754ae1d332e'
down_revision: Union[str, Sequence[str], None] = 'd5cbedacf0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'friends',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('photo_url', sa.String(), nullable=True),
		sa.Column('user_id', sa.Integer(), nullable=False),
		sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
		sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_friends_id'), 'friends', ['id'], unique=False)
	op.create_index(op.f('ix_friends_photo_url'), 'friends', ['photo_url'], unique=False)
	op.create_index(op.f('ix_friends_user_id'), 'friends', ['user_id'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_friends_user_id'), table_name='friends')
	op.drop_index(op.f('ix_friends_photo_url'), table_name='friends')
	op.drop_index(op.f('ix_friends_id'), table_name='friends')
	op.drop_table('friends')
	# ### end Alembic commands ###
