"""add on delete cascade

Revision ID: 588009257fa7
Revises: 04112fe94efe
Create Date: 2025-09-06 18:48:07.668603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588009257fa7'
down_revision: Union[str, Sequence[str], None] = '04112fe94efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key constraints and recreate with CASCADE
    op.drop_constraint('friends_user_id_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key('friends_user_id_fkey', 'friends', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('receipts_user_id_fkey', 'receipts', type_='foreignkey')
    op.create_foreign_key('receipts_user_id_fkey', 'receipts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('items_receipt_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key('items_receipt_id_fkey', 'items', 'receipts', ['receipt_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('variations_item_id_fkey', 'variations', type_='foreignkey')
    op.create_foreign_key('variations_item_id_fkey', 'variations', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('receipt_friend_receipt_id_fkey', 'receipt_friend', type_='foreignkey')
    op.create_foreign_key('receipt_friend_receipt_id_fkey', 'receipt_friend', 'receipts', ['receipt_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('receipt_friend_friend_id_fkey', 'receipt_friend', type_='foreignkey')
    op.create_foreign_key('receipt_friend_friend_id_fkey', 'receipt_friend', 'friends', ['friend_id'], ['id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert foreign key constraints to original state (without CASCADE)
    op.drop_constraint('receipt_friend_friend_id_fkey', 'receipt_friend', type_='foreignkey')
    op.create_foreign_key('receipt_friend_friend_id_fkey', 'receipt_friend', 'friends', ['friend_id'], ['id'])
    
    op.drop_constraint('receipt_friend_receipt_id_fkey', 'receipt_friend', type_='foreignkey')
    op.create_foreign_key('receipt_friend_receipt_id_fkey', 'receipt_friend', 'receipts', ['receipt_id'], ['id'])
    
    op.drop_constraint('variations_item_id_fkey', 'variations', type_='foreignkey')
    op.create_foreign_key('variations_item_id_fkey', 'variations', 'items', ['item_id'], ['id'])
    
    op.drop_constraint('items_receipt_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key('items_receipt_id_fkey', 'items', 'receipts', ['receipt_id'], ['id'])
    
    op.drop_constraint('receipts_user_id_fkey', 'receipts', type_='foreignkey')
    op.create_foreign_key('receipts_user_id_fkey', 'receipts', 'users', ['user_id'], ['id'])
    
    op.drop_constraint('friends_user_id_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key('friends_user_id_fkey', 'friends', 'users', ['user_id'], ['id'])
    
    # ### end Alembic commands ###
