"""add receipt url column

Revision ID: 9c08962df91e
Revises: 038dcf81709c
Create Date: 2025-09-06 15:27:38.950833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c08962df91e'
down_revision: Union[str, Sequence[str], None] = '038dcf81709c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('receipt_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_receipts_receipt_url'), 'receipts', ['receipt_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_receipt_url'), table_name='receipts')
    op.drop_column('receipts', 'receipt_url')
    # ### end Alembic commands ###
