"""add item_friend table

Revision ID: e8da1cb12e2a
Revises: 588009257fa7
Create Date: 2025-09-06 20:30:20.734245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8da1cb12e2a'
down_revision: Union[str, Sequence[str], None] = '588009257fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_friends_friend_id'), 'item_friends', ['friend_id'], unique=False)
    op.create_index(op.f('ix_item_friends_id'), 'item_friends', ['id'], unique=False)
    op.create_index(op.f('ix_item_friends_item_id'), 'item_friends', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_friends_item_id'), table_name='item_friends')
    op.drop_index(op.f('ix_item_friends_id'), table_name='item_friends')
    op.drop_index(op.f('ix_item_friends_friend_id'), table_name='item_friends')
    op.drop_table('item_friends')
    # ### end Alembic commands ###
